### ISSUE TITLE
Running an error.

### ISSUE THREAD

**Issue by yangyangtiaoguo** [lucazanella/AnomalyCLIP#7]
Hello, your work is excellent. I have downloaded the code and deployed the environment according to the process you provided. However, I encountered the following error while further trying to utilize the command test dataset:
```
[2023-11-09 10:46:55,253][__main__][INFO] - Instantiating datamodule <src.data.anomaly_clip_datamodule.AnomalyCLIPDataModule>
[2023-11-09 10:46:55,286][__main__][INFO] - Instantiating model <src.models.anomaly_clip_module.AnomalyCLIPModule>
[2023-11-09 10:46:59,655][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.models.components' has no attribute 'anomaly_clip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/remote-home/share/dmb_nas/wy/docker/coding/big_VAD/AnomalyCLIP-main/src/models/components/anomaly_clip.py", line 8, in <module>
    from src.models.components.clip import clip
  File "/remote-home/share/dmb_nas/wy/docker/coding/big_VAD/AnomalyCLIP-main/src/models/components/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/remote-home/share/dmb_nas/wy/docker/coding/big_VAD/AnomalyCLIP-main/src/models/components/clip/clip.py", line 14, in <module>
    from .simple_tokenizer import SimpleTokenizer as _Tokenizer
  File "/remote-home/share/dmb_nas/wy/docker/coding/big_VAD/AnomalyCLIP-main/src/models/components/clip/simple_tokenizer.py", line 7, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.models.components.anomaly_clip.AnomalyCLIP':
ModuleNotFoundError("No module named 'regex'")
Are you sure that 'anomaly_clip' is importable from module 'src.models.components'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/remote-home/share/dmb_nas/wy/docker/coding/big_VAD/AnomalyCLIP-main/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/eval.py", line 52, in evaluate
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/anaconda3/envs/anomalyclip/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.models.components.anomaly_clip.AnomalyCLIP', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.net
[2023-11-09 10:46:59,671][src.utils.utils][INFO] - Output dir: /remote-home/share/dmb_nas/wy/docker/coding/big_VAD/AnomalyCLIP-main/logs/eval/runs/2023-11-09_10-46-54
Error executing job with overrides: ['model=anomaly_clip_shanghaitech', 'data=shanghaitech', 'ckpt_path=ckpt/checkpoints/shanghaitech/last.ckpt']
Error locating target 'src.models.components.anomaly_clip.AnomalyCLIP', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.net

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I am unable to resolve it and have no clue, I would like to hear from you.

**Comment by luca-zanella-dvl** [comment]
Hi and thank you for your interest in our work! I apologize for the late reply, but I am currently busy with another deadline. I just noticed that we did not include the libraries required by CLIP in the requirements.txt. Can you try the following command in your environment and let me know if it works?

`pip install ftfy regex tqdm`

**Comment by yangyangtiaoguo** [comment]
> Hi and thank you for your interest in our work! I apologize for the late reply, but I am currently busy with another deadline. I just noticed that we did not include the libraries required by CLIP in the requirements.txt. Can you try the following command in your environment and let me know if it works?
> 
> `pip install ftfy regex tqdm`

Hi author, thanks for your reply. The solution you provided is valid and the program works fine. Sorry for the late reply. I've been working on the rebuttal of the article recently.
